import re
import os
from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_TAB_ALIGNMENT, WD_TAB_LEADER
from ..core.logger import logger

def is_sentence_end(text: str) -> bool:
    if not text:
        return True
    end_chars = ('.', '。', '!', '！', '?', '？', ';', '；', ':', '：', '”', '"', "'", '’', '】', ']', ')')
    return text.strip().endswith(end_chars)

def is_heading_or_list(text: str) -> bool:
    text = text.strip()
    if not text:
        return False
    # Matches A., B., A、, B、, (1), ①, 例1, 【知识点】, etc.
    patterns = [
        r'^[A-Z][\.\u3001]',
        r'^\(\d+\)',
        r'^[\u2460-\u2473]', # ①-⑳
        r'^例\s*\d+',
        r'^变式\s*\d+',
        r'^【.*?】',
        r'^\d+[\.\u3001]'
    ]
    for p in patterns:
        if re.match(p, text):
            return True
    return False

def fix_chinese_english_spacing(text: str) -> str:
    # Add space between Chinese and English/Number
    text = re.sub(r'([\u4e00-\u9fa5])([a-zA-Z0-9])', r'\1 \2', text)
    # Add space between English/Number and Chinese
    text = re.sub(r'([a-zA-Z0-9])([\u4e00-\u9fa5])', r'\1 \2', text)

    # Fix math probabilities (e.g., P (A) -> P(A))
    text = re.sub(r'([PCE])\s*\(\s*([A-Za-z0-9_]+)\s*\)', r'\1(\2)', text)
    # Fix fractions (e.g., 1 / 6 -> 1/6)
    text = re.sub(r'(\d+)\s*/\s*(\d+)', r'\1/\2', text)
    # Fix English words broken by spaces (basic heuristic)
    # e.g. "E x a m p l e" -> "Example"
    # This is risky, only applying to single separated letters.
    text = re.sub(r'\b([A-Za-z])\s+([A-Za-z])\b', r'\1\2', text)

    # Extra cleanup
    text = re.sub(r'\s+', ' ', text).strip()
    return text

def apply_heading_styles(paragraph):
    text = paragraph.text.strip()
    if not text:
        return

    # Check for major headings
    is_major_heading = bool(re.match(r'^(【.*?】|专题\s*\d+|第.*?部分|一、|二、|三、|四、|五、)', text))
    is_minor_heading = bool(re.match(r'^(例\s*\d+|变式.*?|考点.*?|\d+\.\s*题型)', text))

    if is_major_heading or is_minor_heading:
        for run in paragraph.runs:
            run.font.bold = True

        # Add spacing before major headings
        if is_major_heading:
            paragraph.paragraph_format.space_before = Pt(12)
            paragraph.paragraph_format.space_after = Pt(6)

def split_glued_toc(text: str) -> list[str]:
    """
    Detects glued TOC lines (e.g. "Section 1...1 Section 2...2")
    and splits them into a list of strings.
    """
    # A typical glued TOC might have dots followed by digits and then more text
    # Let's split by pattern: ...<digits>
    parts = re.split(r'((?:\.{3,}|…+)\s*\d+)', text)
    toc_lines = []
    current_line = ""
    for part in parts:
        current_line += part
        if re.search(r'(?:\.{3,}|…+)\s*\d+$', part):
            toc_lines.append(current_line.strip())
            current_line = ""

    if current_line.strip():
        # Might not have a page number at the very end
        if toc_lines:
             toc_lines[-1] += " " + current_line.strip()
        else:
             toc_lines.append(current_line.strip())

    return toc_lines

def convert_to_table(doc, paras_to_convert: list):
    """
    Converts a list of consecutive paragraphs that look like tabular data into a Word table.
    """
    if not paras_to_convert:
        return

    # Heuristic: split each paragraph by large spaces or tabs
    table_data = []
    max_cols = 0
    for p in paras_to_convert:
        # Split by 2 or more spaces, or tabs
        cols = re.split(r'\s{2,}|\t+', p.text.strip())
        table_data.append(cols)
        max_cols = max(max_cols, len(cols))

    if max_cols < 2:
        return # Not a table

    # Insert table before the first paragraph
    p_element = paras_to_convert[0]._element
    table = doc.add_table(rows=len(table_data), cols=max_cols)
    table.style = 'Table Grid'

    # Move the new table XML immediately before the first paragraph
    p_element.getparent().insert(p_element.getparent().index(p_element), table._element)

    for r_idx, row_data in enumerate(table_data):
        for c_idx, cell_text in enumerate(row_data):
            if c_idx < len(table.columns):
                table.cell(r_idx, c_idx).text = cell_text

    # Delete original paragraphs
    for p in paras_to_convert:
        p_element = p._element
        p_element.getparent().remove(p_element)

def postprocess_docx(filepath: str) -> bool:
    """
    Applies heuristic post-processing to a DOCX file generated by pdf2docx
    to fix common issues with Chinese educational materials (hard breaks, spacing, headers).
    Returns True if processed successfully.
    """
    try:
        doc = Document(filepath)
    except Exception as e:
        logger.error(f"Failed to open DOCX for post-processing: {e}")
        return False

    logger.info("Starting DOCX post-processing heuristics...")

    try:
        # Pass 1: TOC Split and Spacing/Text Replacements
        paras = list(doc.paragraphs)
        i = 0
        while i < len(paras):
            para = paras[i]
            original_text = para.text.strip()
            if not original_text:
                i += 1
                continue

            # 1. Split glued TOC
            # If we see multiple dots...page number...dots...page number in the same para
            if len(re.findall(r'(?:\.{3,}|…+)\s*\d+', original_text)) > 1:
                toc_lines = split_glued_toc(original_text)
                if len(toc_lines) > 1:
                    # Replace current para with first line
                    para.text = fix_chinese_english_spacing(toc_lines[0])
                    # Insert subsequent lines as new paragraphs right after
                    for j in range(1, len(toc_lines)):
                        new_p = doc.add_paragraph(fix_chinese_english_spacing(toc_lines[j]))
                        # Move new_p right after para
                        para._element.getparent().insert(para._element.getparent().index(para._element) + j, new_p._element)
                        paras.insert(i + j, new_p)

                    # Ensure TOC dots are treated reasonably (we won't build a full Word TOC field for now,
                    # but splitting them makes them legible)
                    i += len(toc_lines)
                    continue

            # 2. Regular Spacing
            new_text = fix_chinese_english_spacing(original_text)
            if new_text != original_text:
                para.text = new_text

            apply_heading_styles(para)
            i += 1

        # Pass 2: Table Recovery
        # Detect sequential paragraphs that have 2+ columns separated by large spaces
        paras = list(doc.paragraphs)
        table_buffer = []

        for p in paras:
            text = p.text.strip()
            # If it has tabular structure (multiple columns split by space)
            if re.search(r'\s{2,}|\t+', text) and len(text) > 2:
                table_buffer.append(p)
            else:
                # Flush table buffer if it has 2+ rows
                if len(table_buffer) >= 2:
                    convert_to_table(doc, table_buffer)
                table_buffer = []

        # Flush at the end
        if len(table_buffer) >= 2:
            convert_to_table(doc, table_buffer)

        # Pass 3: Paragraph merging (Hard Break Fixes)
        # Re-fetch paragraphs since we deleted/added some
        paras = list(doc.paragraphs)
        i = 0
        merged_count = 0

        while i < len(paras) - 1:
            p1 = paras[i]
            p2 = paras[i+1]

            t1 = p1.text.strip()
            t2 = p2.text.strip()

            if t1 and t2 and not is_sentence_end(t1) and not is_heading_or_list(t2) and not is_heading_or_list(t1):
                join_char = " " if re.match(r'[a-zA-Z0-9]', t1[-1]) and re.match(r'[a-zA-Z0-9]', t2[0]) else ""
                p1.add_run(join_char + t2)

                p_element = p2._element
                p_element.getparent().remove(p_element)

                paras.pop(i+1)
                merged_count += 1
            else:
                i += 1

        logger.info(f"Post-processing complete. Merged {merged_count} paragraphs.")

        doc.save(filepath)
        return True

    except Exception as e:
        logger.error(f"Error during DOCX post-processing: {e}", exc_info=True)
        return False
