import re
import os
from docx import Document
from docx.shared import Pt
from ..core.logger import logger

def is_sentence_end(text: str) -> bool:
    if not text:
        return True
    end_chars = ('.', '。', '!', '！', '?', '？', ';', '；', ':', '：', '”', '"', "'", '’', '】', ']', ')')
    return text.strip().endswith(end_chars)

def is_heading_or_list(text: str) -> bool:
    text = text.strip()
    if not text:
        return False
    # Matches A., B., A、, B、, (1), ①, 例1, 【知识点】, etc.
    patterns = [
        r'^[A-Z][\.\u3001]',
        r'^\(\d+\)',
        r'^[\u2460-\u2473]', # ①-⑳
        r'^例\s*\d+',
        r'^变式\s*\d+',
        r'^【.*?】',
        r'^\d+[\.\u3001]'
    ]
    for p in patterns:
        if re.match(p, text):
            return True
    return False

def fix_chinese_english_spacing(text: str) -> str:
    # Add space between Chinese and English/Number
    text = re.sub(r'([\u4e00-\u9fa5])([a-zA-Z0-9])', r'\1 \2', text)
    # Add space between English/Number and Chinese
    text = re.sub(r'([a-zA-Z0-9])([\u4e00-\u9fa5])', r'\1 \2', text)

    # Fix math probabilities (e.g., P (A) -> P(A))
    text = re.sub(r'P\s*\(\s*([A-Z])\s*\)', r'P(\1)', text)
    # Fix fractions (e.g., 1 / 6 -> 1/6)
    text = re.sub(r'(\d+)\s*/\s*(\d+)', r'\1/\2', text)
    return text

def apply_heading_styles(paragraph):
    text = paragraph.text.strip()
    if not text:
        return

    # Check for major headings
    is_major_heading = bool(re.match(r'^(【.*?】|专题\s*\d+|第.*?部分|一、|二、|三、|四、|五、)', text))
    is_minor_heading = bool(re.match(r'^(例\s*\d+|变式.*?|考点.*?|\d+\.\s*题型)', text))

    if is_major_heading or is_minor_heading:
        for run in paragraph.runs:
            run.font.bold = True

        # Add spacing before major headings
        if is_major_heading:
            paragraph.paragraph_format.space_before = Pt(12)
            paragraph.paragraph_format.space_after = Pt(6)

def postprocess_docx(filepath: str) -> bool:
    """
    Applies heuristic post-processing to a DOCX file generated by pdf2docx
    to fix common issues with Chinese educational materials (hard breaks, spacing, headers).
    Returns True if processed successfully.
    """
    try:
        doc = Document(filepath)
    except Exception as e:
        logger.error(f"Failed to open DOCX for post-processing: {e}")
        return False

    logger.info("Starting DOCX post-processing heuristics...")

    try:
        # Pass 1: Text replacements and styling
        for para in doc.paragraphs:
            original_text = para.text
            if not original_text.strip():
                continue

            new_text = fix_chinese_english_spacing(original_text)

            # Reconstruct the paragraph text if it changed
            if new_text != original_text:
                # To preserve simple formatting, we replace the text of the first run
                # and clear the rest, or just carefully replace text.
                # A simple approach for now: clear and set new text in first run,
                # but this loses intra-paragraph formatting (colors/fonts).
                # Since pdf2docx often shatters runs, a full rebuild is safer for pure text quality,
                # but might lose colors. For educational texts, readability is priority.

                # A safer approach: only modify text if there's exactly 1 run, OR just overwrite.
                # Given pdf2docx creates many runs, we'll try to just overwrite the whole paragraph text
                # and apply basic styling.
                para.text = new_text

            apply_heading_styles(para)

        # Pass 2: Paragraph merging (Hard Break Fixes)
        # We look at consecutive paragraphs. If p1 doesn't end in sentence terminator,
        # and p2 doesn't start with a heading/list, we merge p2 into p1.

        # We need to iterate carefully as we'll be modifying the XML tree to remove paragraphs
        paras = list(doc.paragraphs)
        i = 0
        merged_count = 0

        while i < len(paras) - 1:
            p1 = paras[i]
            p2 = paras[i+1]

            t1 = p1.text.strip()
            t2 = p2.text.strip()

            # Conditions for merging p2 into p1:
            # 1. p1 is not empty and p2 is not empty
            # 2. p1 does not end with a sentence terminator
            # 3. p2 does not look like a new heading or list item
            # 4. p1 is not a major heading itself
            if t1 and t2 and not is_sentence_end(t1) and not is_heading_or_list(t2) and not is_heading_or_list(t1):
                # Append p2 text to p1 (adding a space if English/Number, otherwise directly)
                join_char = " " if re.match(r'[a-zA-Z0-9]', t1[-1]) and re.match(r'[a-zA-Z0-9]', t2[0]) else ""
                p1.add_run(join_char + t2)

                # Remove p2 from the document XML
                p_element = p2._element
                p_element.getparent().remove(p_element)

                # Update our list (remove p2) so the next iteration checks p1 against p3
                paras.pop(i+1)
                merged_count += 1
            else:
                i += 1

        logger.info(f"Post-processing complete. Merged {merged_count} paragraphs.")

        # Save changes
        doc.save(filepath)
        return True

    except Exception as e:
        logger.error(f"Error during DOCX post-processing: {e}", exc_info=True)
        return False
